# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      REACT_APP_BASENAME: coach-digital
      PUBLIC_URL: ./
      REACT_APP_API_URL: http://173.255.230.140:81

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install
      - run: npm run build
      - name: Publish
        uses: nogsantos/ssh-scp-deploy@v1.3.0
        with:
          src: ./build/*
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/105060288?s=48&v=4
          SLACK_MESSAGE: "Post Content :rocket:"
          SLACK_TITLE: Coach Digital - Deploy done
          SLACK_USERNAME: GitBot
          SLACK_WEBHOOK: https://hooks.slack.com/services/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
